language: python
python:
    - '2.7'
    - '3.6'
    - '3.7'
    - 'nightly'
dist: xenial
env:
    - DJANGO_VERSION=1.11.17
    - DJANGO_VERSION=2.1.4
matrix:
    allow_failures:  # allow failures for non-released versions
        - python: 'nightly'
    exclude:  # Django 2 does not support Python 2.x
        - python: '2.7'
          env: DJANGO_VERSION=2.1.4
install:
    - travis_retry pip install django==$DJANGO_VERSION
    - travis_retry pip install gevent
    - travis_retry pip install psycopg2-binary
    - python setup.py -q install
script:
    - python runtests.py
services:
    - postgresql
before_script:
    - psql -c 'create database test;' -U postgres
